<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>tour.naments &beta;</title>
	<link rel="stylesheet" href="/css/base.css" type="text/css" media="all" />
	<link rel="stylesheet" href="/css/content.css" type="text/css" media="all" />
</head>

<body>
	<div id="wrap">

		<div class="half left">
			<div class="splash_box">

				<h1><a href="/">tour.naments &beta;</a></h1>
				<p>Welcome to tour.naments, the simple tournament manager.</p>

				<h2>Latest Updates</h2>
				<p>November 7, 2010 - Initial beta launch.</p>

			</div>
		</div>

		<div class="half right">
				<?php echo $this->layout()->content ?>
		</div>

		<div id="footer">
			&copy; <?php echo date('Y') ?> <a href="/">tour.naments</a>
		</div>

	</div>

</body>
</html>
