<div class="tournament16-wrap">
	<div class="round5-top winner5"><?php echo $this->bracketPosition(30) ?></div>

	<div class="round4-topwrap">
		<div class="round4-top"><?php echo $this->bracketPosition(28) ?></div>
		<div class="round3-topwrap">
			<div class="round3-top"><?php echo $this->bracketPosition(24) ?></div>
			<div class="round2-topwrap">
				<div class="round2-top"><?php echo $this->bracketPosition(16) ?></div>
				<div class="round1-top"><?php echo $this->bracketPosition(0) ?></div>

				<div class="round1-bottom"><?php echo $this->bracketPosition(15) ?></div>
			</div>
			<div class="round2-bottomwrap">
				<div class="round2-bottom"><?php echo $this->bracketPosition(23) ?></div>
				<div class="round1-top"><?php echo $this->bracketPosition(7) ?></div>
				<div class="round1-bottom"><?php echo $this->bracketPosition(8) ?></div>
			</div>

		</div>
		<div class="round3-bottomwrap">
			<div class="round3-bottom"><?php echo $this->bracketPosition(27) ?></div>
			<div class="round2-topwrap">
				<div class="round2-top"><?php echo $this->bracketPosition(19) ?></div>
				<div class="round1-top"><?php echo $this->bracketPosition(3) ?></div>
				<div class="round1-bottom"><?php echo $this->bracketPosition(12) ?></div>

			</div>
			<div class="round2-bottomwrap">
				<div class="round2-bottom"><?php echo $this->bracketPosition(20) ?></div>
				<div class="round1-top"><?php echo $this->bracketPosition(4) ?></div>
				<div class="round1-bottom"><?php echo $this->bracketPosition(11) ?></div>
			</div>
		</div>

	</div>
	<div class="round4-bottomwrap">
		<div class="round4-bottom"><?php echo $this->bracketPosition(29) ?></div>
		<div class="round3-topwrap">
			<div class="round3-top"><?php echo $this->bracketPosition(25) ?></div>
			<div class="round2-topwrap">
				<div class="round2-top"><?php echo $this->bracketPosition(17) ?></div>

				<div class="round1-top"><?php echo $this->bracketPosition(1) ?></div>
				<div class="round1-bottom"><?php echo $this->bracketPosition(14) ?></div>
			</div>
			<div class="round2-bottomwrap">
				<div class="round2-bottom"><?php echo $this->bracketPosition(22) ?></div>
				<div class="round1-top"><?php echo $this->bracketPosition(6) ?></div>
				<div class="round1-bottom"><?php echo $this->bracketPosition(9) ?></div>

			</div>
		</div>
		<div class="round3-bottomwrap">
			<div class="round3-bottom"><?php echo $this->bracketPosition(26) ?></div>
			<div class="round2-topwrap">
				<div class="round2-top"><?php echo $this->bracketPosition(18) ?></div>
				<div class="round1-top"><?php echo $this->bracketPosition(2) ?></div>

				<div class="round1-bottom"><?php echo $this->bracketPosition(13) ?></div>
			</div>
			<div class="round2-bottomwrap">
				<div class="round2-bottom"><?php echo $this->bracketPosition(21) ?></div>
				<div class="round1-top"><?php echo $this->bracketPosition(5) ?></div>
				<div class="round1-bottom"><?php echo $this->bracketPosition(10) ?></div>
			</div>

		</div>
	</div>
</div>
