<div class="tournament32-wrap">
	<div class="round6-top winner6"><?php echo $this->bracketPosition(62) ?></div>

	<div class="round5-topwrap">
		<div class="round5-top"><?php echo $this->bracketPosition(60) ?></div>
		<div class="round4-topwrap">
			<div class="round4-top"><?php echo $this->bracketPosition(56) ?></div>
			<div class="round3-topwrap">
				<div class="round3-top"><?php echo $this->bracketPosition(48) ?></div>
				<div class="round2-topwrap">

					<div class="round2-top"><?php echo $this->bracketPosition(32) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(0) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(31) ?></div>
				</div>
				<div class="round2-bottomwrap">
					<div class="round2-bottom"><?php echo $this->bracketPosition(47) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(15) ?></div>

					<div class="round1-bottom"><?php echo $this->bracketPosition(16) ?></div>
				</div>
			</div>
			<div class="round3-bottomwrap">
				<div class="round3-bottom"><?php echo $this->bracketPosition(55) ?></div>
				<div class="round2-topwrap">
					<div class="round2-top"><?php echo $this->bracketPosition(39) ?></div>

					<div class="round1-top"><?php echo $this->bracketPosition(7) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(24) ?></div>
				</div>
				<div class="round2-bottomwrap">
					<div class="round2-bottom"><?php echo $this->bracketPosition(40) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(8) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(23) ?></div>

				</div>
			</div>
		</div>
		<div class="round4-bottomwrap">
			<div class="round4-bottom"><?php echo $this->bracketPosition(59) ?></div>
			<div class="round3-topwrap">
				<div class="round3-top"><?php echo $this->bracketPosition(51) ?></div>
				<div class="round2-topwrap">

					<div class="round2-top"><?php echo $this->bracketPosition(35) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(3) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(28) ?></div>
				</div>
				<div class="round2-bottomwrap">
					<div class="round2-bottom"><?php echo $this->bracketPosition(44) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(12) ?></div>

					<div class="round1-bottom"><?php echo $this->bracketPosition(19) ?></div>
				</div>
			</div>
			<div class="round3-bottomwrap">
				<div class="round3-bottom"><?php echo $this->bracketPosition(52) ?></div>
				<div class="round2-topwrap">
					<div class="round2-top"><?php echo $this->bracketPosition(36) ?></div>

					<div class="round1-top"><?php echo $this->bracketPosition(4) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(27) ?></div>
				</div>
				<div class="round2-bottomwrap">
					<div class="round2-bottom"><?php echo $this->bracketPosition(43) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(11) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(20) ?></div>

				</div>
			</div>
		</div>
	</div>
	<div class="round5-bottomwrap">
		<div class="round5-bottom"><?php echo $this->bracketPosition(61) ?></div>
		<div class="round4-topwrap">
			<div class="round4-top"><?php echo $this->bracketPosition(57) ?></div>

			<div class="round3-topwrap">
				<div class="round3-top"><?php echo $this->bracketPosition(49) ?></div>
				<div class="round2-topwrap">
					<div class="round2-top"><?php echo $this->bracketPosition(33) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(1) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(30) ?></div>
				</div>

				<div class="round2-bottomwrap">
					<div class="round2-bottom"><?php echo $this->bracketPosition(46) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(14) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(17) ?></div>
				</div>
			</div>
			<div class="round3-bottomwrap">

				<div class="round3-bottom"><?php echo $this->bracketPosition(54) ?></div>
				<div class="round2-topwrap">
					<div class="round2-top"><?php echo $this->bracketPosition(38) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(6) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(25) ?></div>
				</div>
				<div class="round2-bottomwrap">

					<div class="round2-bottom"><?php echo $this->bracketPosition(41) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(9) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(22) ?></div>
				</div>
			</div>
		</div>
		<div class="round4-bottomwrap">

			<div class="round4-bottom"><?php echo $this->bracketPosition(58) ?></div>
			<div class="round3-topwrap">
				<div class="round3-top"><?php echo $this->bracketPosition(50) ?></div>
				<div class="round2-topwrap">
					<div class="round2-top"><?php echo $this->bracketPosition(34) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(2) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(29) ?></div>

				</div>
				<div class="round2-bottomwrap">
					<div class="round2-bottom"><?php echo $this->bracketPosition(45) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(13) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(18) ?></div>
				</div>
			</div>

			<div class="round3-bottomwrap">
				<div class="round3-bottom"><?php echo $this->bracketPosition(53) ?></div>
				<div class="round2-topwrap">
					<div class="round2-top"><?php echo $this->bracketPosition(37) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(5) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(26) ?></div>

				</div>
				<div class="round2-bottomwrap">
					<div class="round2-bottom"><?php echo $this->bracketPosition(42) ?></div>
					<div class="round1-top"><?php echo $this->bracketPosition(10) ?></div>
					<div class="round1-bottom"><?php echo $this->bracketPosition(21) ?></div>
				</div>
			</div>

		</div>
	</div>
</div>
