<div class="tournament4-wrap">
	<div class="round3-top winner3"><?php echo $this->bracketPosition(6) ?></div>

	<div class="round2-topwrap">
		<div class="round2-top"><?php echo $this->bracketPosition(4) ?></div>
		<div class="round1-top"><?php echo $this->bracketPosition(0) ?></div>
		<div class="round1-bottom"><?php echo $this->bracketPosition(3) ?></div>
	</div>
	<div class="round2-bottomwrap">
		<div class="round2-bottom"><?php echo $this->bracketPosition(5) ?></div>

		<div class="round1-top"><?php echo $this->bracketPosition(1) ?></div>
		<div class="round1-bottom"><?php echo $this->bracketPosition(2) ?></div>
	</div>
</div>
