<div class="tournament8-wrap">
	<div class="round4-top winner4"><?php echo $this->bracketPosition(14) ?></div>

	<div class="round3-topwrap">
		<div class="round3-top"><?php echo $this->bracketPosition(12) ?></div>
		<div class="round2-topwrap">
			<div class="round2-top"><?php echo $this->bracketPosition(8) ?></div>
			<div class="round1-top"><?php echo $this->bracketPosition(0) ?></div>
			<div class="round1-bottom"><?php echo $this->bracketPosition(7) ?></div>
		</div>

		<div class="round2-bottomwrap">
			<div class="round2-bottom"><?php echo $this->bracketPosition(11) ?></div>
			<div class="round1-top"><?php echo $this->bracketPosition(3) ?></div>
			<div class="round1-bottom"><?php echo $this->bracketPosition(4) ?></div>
		</div>
	</div>
	<div class="round3-bottomwrap">

		<div class="round3-bottom"><?php echo $this->bracketPosition(13) ?></div>
		<div class="round2-topwrap">
			<div class="round2-top"><?php echo $this->bracketPosition(9) ?></div>
			<div class="round1-top"><?php echo $this->bracketPosition(1) ?></div>
			<div class="round1-bottom"><?php echo $this->bracketPosition(6) ?></div>
		</div>
		<div class="round2-bottomwrap">

			<div class="round2-bottom"><?php echo $this->bracketPosition(10) ?></div>
			<div class="round1-top"><?php echo $this->bracketPosition(2) ?></div>
			<div class="round1-bottom"><?php echo $this->bracketPosition(5) ?></div>
		</div>
	</div>
</div>
